site_name: Molecular Dynamics
site_url: https://dgoppenheimer.github.io/mk-test/
theme:
  name: material
  custom_dir: docs/overrides/
  palette:
    primary: blue
  logo: assets/logo.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

site_author: David G Oppenheimer
site_description: >-
  Notes on carrying out and analyzing the results from molecular dynamics simulations

# Copyright
copyright: Copyright &copy; 2022 David G Oppenheimer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - footnotes





