site_name: Molecular Dynamics
site_url: https://dgoppenheimer.github.io/mk-test/
theme:
  name: material
  custom_dir: docs/overrides/
  palette:
    primary: blue
  logo: assets/logo.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.highlight


site_author: David G Oppenheimer
site_description: >-
  Notes for running and analyzing molecular dynamics simulations

# Copyright
copyright: Copyright &copy; 2022 David G Oppenheimer

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: ./index.md
  - User Guide:
    - Introduction: user-guide/introduction.md
    - Getting Started: user-guide/getting-started.md
    - Building This Site: user-guide/building-this-site.md
    - user-guide/using-plotly.md
    - MD Analysis:
      - MD Analysis with VMD: user-guide/md-analysis/analysis-vmd.md
  - Reference: 
    - reference/ligplot.md
    - reference/ligpargen.md
    - reference/gromacs-tutorials.md
    - reference/docking-tutorials.md
    - reference/using-vmd.md
    - reference/conda-colab.md

  - Course: 
    - course/index.md
    - Course Organization: course/course-organization.md
    - Lab 00: course/lab00.md
    - Lab 01: course/lab01.md

plugins:
    - mkdocs-video


